CREATE DATABASE ATIVIDADE;
USE ATIVIDADE;

CREATE TABLE ADVOGADO (
	IDADVOGADO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45),
    CPF VARCHAR(14),
    DATA_NASCIMENTO VARCHAR(10),
    ENDERECO VARCHAR(45),
    OAB VARCHAR(15),
    PRIMARY KEY (IRDPESSOA)
);

CREATE TABLE PROCESSO (
	IDPROCESSO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    IDADVOGADO INT UNSIGNED NOT NULL,
	ESTADO VARCHAR(45),
    NOME VARCHAR(45),
    PRIMARY KEY (IDPROCESSO),
    FOREIGN KEY (IDADVOGADO) REFERENCES ADVOGADO (IDADVOGADO)
);